/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6_douglasrubi;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author famii
 */
public class MENU extends javax.swing.JFrame {

    /**
     * Creates new form MENU
     */
    DefaultMutableTreeNode rootEstudiantes;
    public MENU() {
        initComponents();
        rootEstudiantes = new DefaultMutableTreeNode("Estudiantes");
        
        
        
    }
    private String Genero = "";
    private ArrayList<Estudiantes> Estudiantes = new ArrayList<>();
    private ArrayList<Maestros> Maestro = new ArrayList<>();
    private ArrayList<Carrera> Carrera = new ArrayList<>();
    private ArrayList<Clases> Clases = new ArrayList<>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        JlbNombreA = new javax.swing.JLabel();
        TxtNombreE = new javax.swing.JTextField();
        JlbApellidoA = new javax.swing.JLabel();
        TxtApellidosE = new javax.swing.JTextField();
        JlbEdadA = new javax.swing.JLabel();
        TxtEdadE = new javax.swing.JTextField();
        JlbGeneroA = new javax.swing.JLabel();
        rbtnME = new javax.swing.JRadioButton();
        rbtnFE = new javax.swing.JRadioButton();
        JlbCuentaA = new javax.swing.JLabel();
        TxtCuentaE = new javax.swing.JTextField();
        JlbCarreraA = new javax.swing.JLabel();
        TxtCarreraE = new javax.swing.JTextField();
        TxtNombreM = new javax.swing.JTextField();
        jlbApellidoM = new javax.swing.JLabel();
        TxtApellidoM = new javax.swing.JTextField();
        jlbEdadM = new javax.swing.JLabel();
        TxtEdadM = new javax.swing.JTextField();
        jlbNombreM = new javax.swing.JLabel();
        JlbGeneroM = new javax.swing.JLabel();
        rbtnMM = new javax.swing.JRadioButton();
        rbtnFM = new javax.swing.JRadioButton();
        JlbClasesM = new javax.swing.JLabel();
        TxtClasesM = new javax.swing.JTextField();
        TxtNombreC = new javax.swing.JTextField();
        jlbApellidoM1 = new javax.swing.JLabel();
        TxtFacultadC = new javax.swing.JTextField();
        jlbEdadM1 = new javax.swing.JLabel();
        TxtMensualidadC = new javax.swing.JTextField();
        jlbNombreM1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TxtJefeC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtClaseC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtSeccionC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtEdificioC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtSalonC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rbtnSiC = new javax.swing.JRadioButton();
        rbtnNoC = new javax.swing.JRadioButton();
        btnAgregarE = new javax.swing.JButton();
        btnAgregarM = new javax.swing.JButton();
        btnAgregarCa = new javax.swing.JButton();
        btnAgregarC = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jlistE = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        JlistM = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        JlistCa = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        JlistC = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jTree1);

        JlbNombreA.setText("Nombre:");

        TxtNombreE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreEActionPerformed(evt);
            }
        });

        JlbApellidoA.setText("Apellido:");

        JlbEdadA.setText("Edad:");

        JlbGeneroA.setText("Genero:");

        rbtnME.setText("M");
        rbtnME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMEActionPerformed(evt);
            }
        });

        rbtnFE.setText("F");
        rbtnFE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFEActionPerformed(evt);
            }
        });

        JlbCuentaA.setText("N° Cuenta:");

        JlbCarreraA.setText("Carrera:");

        TxtNombreM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreMActionPerformed(evt);
            }
        });

        jlbApellidoM.setText("Apellido:");

        jlbEdadM.setText("Edad:");

        jlbNombreM.setText("Nombre:");

        JlbGeneroM.setText("Genero:");

        rbtnMM.setText("M");
        rbtnMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMMActionPerformed(evt);
            }
        });

        rbtnFM.setText("F");
        rbtnFM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFMActionPerformed(evt);
            }
        });

        JlbClasesM.setText("Clases:");

        TxtNombreC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreCActionPerformed(evt);
            }
        });

        jlbApellidoM1.setText("Facultad:");

        jlbEdadM1.setText("Mensualidad:");

        jlbNombreM1.setText("Nombre:");

        jLabel1.setText("Jefe Carrera:");

        TxtJefeC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtJefeCActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre Clase:");

        TxtClaseC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtClaseCActionPerformed(evt);
            }
        });

        jLabel3.setText("Seccion:");

        jLabel4.setText("Edificio:");

        jLabel5.setText("Salon:");

        jLabel6.setText("Aire Acondicionado");

        rbtnSiC.setText("Si");

        rbtnNoC.setText("No");

        btnAgregarE.setText("AgregarE");
        btnAgregarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEActionPerformed(evt);
            }
        });

        btnAgregarM.setText("AgregarM");
        btnAgregarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMActionPerformed(evt);
            }
        });

        btnAgregarCa.setText("AgregarCa");
        btnAgregarCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCaActionPerformed(evt);
            }
        });

        btnAgregarC.setText("AgregarC");

        jlistE.setModel(new DefaultListModel());
        jScrollPane5.setViewportView(jlistE);

        JlistM.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(JlistM);

        JlistCa.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(JlistCa);

        JlistC.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(JlistC);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(JlbNombreA)
                            .addGap(18, 18, 18)
                            .addComponent(TxtNombreE, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(JlbApellidoA)
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(JlbEdadA)
                                    .addGap(35, 35, 35)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtApellidosE)
                                .addComponent(TxtEdadE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JlbGeneroA)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnME)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnFE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JlbCarreraA)
                        .addGap(32, 32, 32)
                        .addComponent(TxtCarreraE, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAgregarE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JlbCuentaA)
                        .addGap(18, 18, 18)
                        .addComponent(TxtCuentaE, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jlbNombreM)
                                    .addGap(18, 18, 18)
                                    .addComponent(TxtNombreM, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jlbApellidoM)
                                            .addGap(18, 18, 18))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jlbEdadM)
                                            .addGap(35, 35, 35)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TxtApellidoM)
                                        .addComponent(TxtEdadM, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JlbGeneroM)
                                    .addComponent(JlbClasesM))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtClasesM, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbtnMM)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbtnFM)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jlbNombreM1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                                .addComponent(TxtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jlbApellidoM1)
                                                    .addComponent(jlbEdadM1)
                                                    .addComponent(jLabel1))
                                                .addGap(35, 35, 35)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(TxtFacultadC, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                                    .addComponent(TxtMensualidadC, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                                    .addComponent(TxtJefeC))))
                                        .addGap(54, 54, 54)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TxtEdificioC)
                                            .addComponent(TxtSalonC)
                                            .addComponent(TxtClaseC)
                                            .addComponent(TxtSeccionC))
                                        .addContainerGap())
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(296, 296, 296)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbtnSiC)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbtnNoC)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(281, 281, 281)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregarM)
                                .addGap(143, 143, 143)
                                .addComponent(btnAgregarCa)
                                .addGap(155, 155, 155)
                                .addComponent(btnAgregarC))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JlbNombreA)
                            .addComponent(TxtNombreE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JlbApellidoA)
                            .addComponent(TxtApellidosE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JlbEdadA)
                            .addComponent(TxtEdadE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbNombreM)
                            .addComponent(TxtNombreM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbApellidoM)
                            .addComponent(TxtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbEdadM)
                            .addComponent(TxtEdadM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TxtNombreC)
                                .addComponent(jLabel2)
                                .addComponent(TxtClaseC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlbNombreM1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbApellidoM1)
                            .addComponent(TxtFacultadC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(TxtSeccionC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtMensualidadC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbEdadM1)
                            .addComponent(jLabel4)
                            .addComponent(TxtEdificioC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(TxtSalonC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(JlbGeneroM)
                                        .addComponent(rbtnMM)
                                        .addComponent(rbtnFM))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(JlbGeneroA)
                                        .addComponent(rbtnME)
                                        .addComponent(rbtnFE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(JlbCuentaA)
                                            .addComponent(TxtCuentaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)
                                            .addComponent(rbtnSiC)
                                            .addComponent(rbtnNoC)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(JlbClasesM)
                                            .addComponent(TxtClasesM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(TxtJefeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JlbCarreraA)
                                    .addComponent(TxtCarreraE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addComponent(btnAgregarE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAgregarM)
                                    .addComponent(btnAgregarCa)
                                    .addComponent(btnAgregarC))))
                        .addGap(37, 37, 37)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane5)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNombreEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreEActionPerformed
        
    }//GEN-LAST:event_TxtNombreEActionPerformed

    private void rbtnFEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFEActionPerformed
        if (this.rbtnFE.isSelected()) {
            this.Genero = "F";
        }
    }//GEN-LAST:event_rbtnFEActionPerformed

    private void TxtNombreMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreMActionPerformed
        
    }//GEN-LAST:event_TxtNombreMActionPerformed

    private void rbtnFMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFMActionPerformed
        if (this.rbtnFM.isSelected()) {
            this.Genero = "F";
        }
    }//GEN-LAST:event_rbtnFMActionPerformed

    private void TxtNombreCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreCActionPerformed
        
    }//GEN-LAST:event_TxtNombreCActionPerformed

    private void TxtJefeCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtJefeCActionPerformed
       
    }//GEN-LAST:event_TxtJefeCActionPerformed

    private void TxtClaseCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtClaseCActionPerformed
        
    }//GEN-LAST:event_TxtClaseCActionPerformed

    private void btnAgregarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEActionPerformed
        boolean valido = true;
        if (this.TxtNombreE.getText() == null || "".equals(this.TxtNombreE.getText())) {
            JOptionPane.showConfirmDialog(this, "Ingrese el nombre");
           valido = false;
        }
        if (this.TxtApellidosE.getText() == null || "".equals(this.TxtApellidosE.getText())) {
            JOptionPane.showConfirmDialog(this, "Ingrese el apellido");
            valido = false;
        }
        if (this.TxtEdadE.getText() == null || "".equals(this.TxtEdadE.getText())) {
            JOptionPane.showConfirmDialog(this, "Ingrese la edad");
            valido = false;
        }
        if (this.Genero == null || "".equals(this.Genero)) {
            JOptionPane.showConfirmDialog(this, "Ingrese el genero");
            valido = false;
        }
        if (this.TxtCuentaE.getText() == null || "".equals(this.TxtCuentaE.getText())) {
            JOptionPane.showConfirmDialog(this, "Ingrese el numero de cuenta");
            valido = false;
        }
        if (this.TxtCarreraE.getText() == null || "".equals(this.TxtCarreraE.getText())) {
            JOptionPane.showConfirmDialog(this, "Ingrese la carrera");
            valido = false;
        }
        if(valido) {
            // String Nombre, String Apellido, int Edad, String Genero,int NumeroCuenta, String Carrera
            Estudiantes estu = new Estudiantes(TxtNombreE.getText(), TxtApellidosE.getText(), Integer.parseInt(TxtEdadE.getText()),  this.Genero, Integer.parseInt(TxtCuentaE.getText()), TxtCarreraE.getText());
            this.Estudiantes.add(estu);
            DefaultListModel modelo
                = (DefaultListModel) jlistE.getModel();

            modelo.addElement(estu);
            this.jlistE.setModel(modelo);
           

        }
    }//GEN-LAST:event_btnAgregarEActionPerformed

    private void rbtnMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMEActionPerformed
        if (this.rbtnME.isSelected()) {
            this.Genero = "M";
        }
    }//GEN-LAST:event_rbtnMEActionPerformed

    private void btnAgregarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMActionPerformed
        boolean valido = true;
        if (this.TxtNombreM.getText() == null || "".equals(this.TxtNombreM.getText())) {
            JOptionPane.showConfirmDialog(this, "Ingrese el nombre");
           valido = false;
        }
        if (this.TxtApellidoM.getText() == null || "".equals(this.TxtApellidoM.getText())) {
            JOptionPane.showConfirmDialog(this, "Ingrese el apellido");
            valido = false;
        }
        if (this.TxtEdadM.getText() == null || "".equals(this.TxtEdadM.getText())) {
            JOptionPane.showConfirmDialog(this, "Ingrese la edad");
            valido = false;
        }
        if (this.Genero == null || "".equals(this.Genero)) {
            JOptionPane.showConfirmDialog(this, "Ingrese el genero");
            valido = false;
        }
        if (this.TxtClasesM.getText() == null || "".equals(this.TxtClasesM.getText())) {
            JOptionPane.showConfirmDialog(this, "Ingrese la lista de clases");
            valido = false;
        }
        if(valido) {
            Maestros Mr = new Maestros(TxtNombreM.getText(), TxtApellidoM.getText(), Integer.parseInt(TxtEdadE.getText()),  this.Genero, Integer.parseInt(TxtClasesM.getText()));
            this.Maestro.add(Mr);
            DefaultListModel modelo
                = (DefaultListModel) jlistE.getModel();

            modelo.addElement(Mr);
            this.jlistE.setModel(modelo);
           

        }
    }//GEN-LAST:event_btnAgregarMActionPerformed

    private void rbtnMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMMActionPerformed
        if (this.rbtnMM.isSelected()) {
            this.Genero = "M";
        }
    }//GEN-LAST:event_rbtnMMActionPerformed

    private void btnAgregarCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCaActionPerformed
         boolean valido = true;
        if (this.TxtNombreC.getText() == null || "".equals(this.TxtNombreC.getText())) {
            JOptionPane.showConfirmDialog(this, "Ingrese el nombre");
           valido = false;
        }
        if (this.TxtFacultadC.getText() == null || "".equals(this.TxtFacultadC.getText())) {
            JOptionPane.showConfirmDialog(this, "Ingrese la facultad");
            valido = false;
        }
        if (this.TxtMensualidadC.getText() == null || "".equals(this.TxtMensualidadC.getText())) {
            JOptionPane.showConfirmDialog(this, "Ingrese la mensualidad");
            valido = false;
        }
        if (this.TxtJefeC.getText() == null || "".equals(this.TxtJefeC.getText())) {
            JOptionPane.showConfirmDialog(this, "Ingrese el jefe de carrera");
            valido = false;
        }
        if(valido) {
            Carrera Car = new Carrera(TxtNombreC.getText(), TxtFacultadC.getText(), Integer.parseInt(TxtMensualidadC.getText()), TxtJefeC.getText());
            this.Carrera.add(Car);
            DefaultListModel modelo
                = (DefaultListModel) jlistE.getModel();

            modelo.addElement(Car);
            this.jlistE.setModel(modelo);
        }
    }//GEN-LAST:event_btnAgregarCaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlbApellidoA;
    private javax.swing.JLabel JlbCarreraA;
    private javax.swing.JLabel JlbClasesM;
    private javax.swing.JLabel JlbCuentaA;
    private javax.swing.JLabel JlbEdadA;
    private javax.swing.JLabel JlbGeneroA;
    private javax.swing.JLabel JlbGeneroM;
    private javax.swing.JLabel JlbNombreA;
    private javax.swing.JList<String> JlistC;
    private javax.swing.JList<String> JlistCa;
    private javax.swing.JList<String> JlistM;
    private javax.swing.JTextField TxtApellidoM;
    private javax.swing.JTextField TxtApellidosE;
    private javax.swing.JTextField TxtCarreraE;
    private javax.swing.JTextField TxtClaseC;
    private javax.swing.JTextField TxtClasesM;
    private javax.swing.JTextField TxtCuentaE;
    private javax.swing.JTextField TxtEdadE;
    private javax.swing.JTextField TxtEdadM;
    private javax.swing.JTextField TxtEdificioC;
    private javax.swing.JTextField TxtFacultadC;
    private javax.swing.JTextField TxtJefeC;
    private javax.swing.JTextField TxtMensualidadC;
    private javax.swing.JTextField TxtNombreC;
    private javax.swing.JTextField TxtNombreE;
    private javax.swing.JTextField TxtNombreM;
    private javax.swing.JTextField TxtSalonC;
    private javax.swing.JTextField TxtSeccionC;
    private javax.swing.JButton btnAgregarC;
    private javax.swing.JButton btnAgregarCa;
    private javax.swing.JButton btnAgregarE;
    private javax.swing.JButton btnAgregarM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel jlbApellidoM;
    private javax.swing.JLabel jlbApellidoM1;
    private javax.swing.JLabel jlbEdadM;
    private javax.swing.JLabel jlbEdadM1;
    private javax.swing.JLabel jlbNombreM;
    private javax.swing.JLabel jlbNombreM1;
    private javax.swing.JList jlistE;
    private javax.swing.JRadioButton rbtnFE;
    private javax.swing.JRadioButton rbtnFM;
    private javax.swing.JRadioButton rbtnME;
    private javax.swing.JRadioButton rbtnMM;
    private javax.swing.JRadioButton rbtnNoC;
    private javax.swing.JRadioButton rbtnSiC;
    // End of variables declaration//GEN-END:variables
}
